import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        chart: {
          "1": "var(--chart-1)",
          "2": "var(--chart-2)",
          "3": "var(--chart-3)",
          "4": "var(--chart-4)",
          "5": "var(--chart-5)",
        },
        // OneAI Custom Colors
        "surface-container": "#e7eeff",
        "surface-container-low": "#f0f3ff",
        "primary-fixed": "#dbe1ff",
        "tertiary-fixed": "#acedff",
        "tertiary-container": "#00788c",
        "on-tertiary": "#ffffff",
        "secondary-container": "#dae2fd",
        "on-primary-container": "#eeefff",
        "on-secondary-fixed": "#131b2e",
        "on-tertiary-container": "#d7f6ff",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#ecf1ff",
        "on-primary": "#ffffff",
        "on-background": "#111c2d",
        "surface-container-highest": "#d8e3fb",
        "secondary-fixed-dim": "#bec6e0",
        "secondary-fixed": "#dae2fd",
        "on-secondary-container": "#5c647a",
        "on-error": "#ffffff",
        "inverse-surface": "#263143",
        "surface-bright": "#f9f9ff",
        "inverse-primary": "#b4c5ff",
        "outline-variant": "#c3c6d7",
        "surface": "#f9f9ff",
        "on-tertiary-fixed-variant": "#004e5c",
        "tertiary-fixed-dim": "#4cd7f6",
        "surface-container-high": "#dee8ff",
        "on-primary-fixed": "#00174b",
        "on-tertiary-fixed": "#001f26",
        "on-surface": "#111c2d",
        "surface-dim": "#cfdaf2",
        "primary-container": "#2563eb",
        "on-primary-fixed-variant": "#003ea8",
        "primary-fixed-dim": "#b4c5ff",
        "error-container": "#ffdad6",
        "on-surface-variant": "#434655",
        "tertiary": "#005e6e",
        "on-secondary-fixed-variant": "#3f465c",
        "surface-tint": "#0053db",
        "surface-container-lowest": "#ffffff",
        "outline": "#737686",
        "surface-variant": "#d8e3fb",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        DEFAULT: "0.25rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "2xl": "48px",
        gutter: "24px",
        xl: "32px",
        "margin-desktop": "32px",
        sm: "8px",
        md: "16px",
        "3xl": "64px",
        lg: "24px",
        xs: "4px",
        base: "4px",
        "margin-mobile": "16px",
      },
    },
  },
  plugins: [],
};
export default config;
